### ISSUE TITLE
Cannot recognize excel file 

### ISSUE THREAD

**Issue by apchenjun** [ghost1face/FileTypeInterrogator#3]
xls/xlsx extension name  can't recognize

**Comment by ghost1face** [comment]
I'm afraid that's not enough information. Do you have an example or sample file?

**Comment by apchenjun** [comment]
@ghost1face 
I uploaded process.xlsx but FileTypeInterrogator
Think it is a jar file
![image](https://user-images.githubusercontent.com/4964551/144952926-89716f77-ef8a-4ff5-91fc-f3993aef95e0.png)

![image](https://user-images.githubusercontent.com/4964551/144952960-e41ef085-39c8-48bc-8617-8ba4a15896c5.png)

**Comment by ghost1face** [comment]
Well it looks like your excel file's first 6-10 bytes match one of the signatures for a java archive.  How did you create the file? I'd say it doesn't have a valid signature created from the application you used to create the file

**Comment by ttnithi** [comment]
XLSX is working fine. But XLS comes back as PPS (power point slideshow).

**Comment by ghost1face** [comment]
I'm going to need some sample files @ttnithi current state, all tests pass against all file types

**Comment by ttnithi** [comment]
[TestingXLSFile.xls](https://github.com/ghost1face/FileTypeInterrogator/files/7840858/TestingXLSFile.xls)
I saved this file as "Excel 97-2003 workbook (*.xls)" format. Today when I tested the attached file, it comes back with type "pcx".

**Comment by ghost1face** [comment]
Thanks for the sample, I'll take a look at it later today.  Out of curiosity, what editor/tool did you use to open and save the file?

**Comment by ttnithi** [comment]
> Thanks for the sample, I'll take a look at it later today. Out of curiosity, what editor/tool did you use to open and save the file?

I used Excel from Microsoft 365

**Comment by ttnithi** [comment]
Please keep me posted.

**Comment by ghost1face** [comment]
I think I've got it, but now I'm wondering if I should test against all other files created from Office365 now just to be sure we cover the other file types.  I'll have a look at those as well in a bit

**Comment by ghost1face** [comment]
#6 should resolve the issues, let me know if you see another type that may be acting funny
